# Generated by Django 5.2.6

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmember',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='management',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='recentactivities',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='accesstoinformation',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='procurementreport',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='mdnote',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='chairmannote',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='pressrelease',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='webstory',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='psspeech',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='successstory',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='tender',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='eoi',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['id']},
        ),
    ]