# Generated by Django 5.2.6 on 2026-01-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ordering_fix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesstoinformation',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Access to Information'},
        ),
        migrations.AlterModelOptions(
            name='boardmember',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Board Members'},
        ),
        migrations.AlterModelOptions(
            name='chairmannote',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Chairman Notes'},
        ),
        migrations.AlterModelOptions(
            name='eoi',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'EOIs'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['created_at'], 'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='management',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Management'},
        ),
        migrations.AlterModelOptions(
            name='mdnote',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'MD Notes'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Policies'},
        ),
        migrations.AlterModelOptions(
            name='pressrelease',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Press Releases'},
        ),
        migrations.AlterModelOptions(
            name='procurementreport',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Procurement Reports'},
        ),
        migrations.AlterModelOptions(
            name='psspeech',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'PS Speeches'},
        ),
        migrations.AlterModelOptions(
            name='recentactivities',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Recent Activities'},
        ),
        migrations.AlterModelOptions(
            name='successstory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Success Stories'},
        ),
        migrations.AlterModelOptions(
            name='tender',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Tenders'},
        ),
        migrations.AlterModelOptions(
            name='webstory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Web Stories'},
        ),
    ]
