from django.urls import path
from.import views

urlpatterns = [
    path('act/', views.act_view, name='act'),
    path('access/', views.access_view, name='access'),
    path('benefits/', views.benefits_view, name='benefits'),
    path('board/', views.board_view, name='board'),
    path('business/', views.business_view, name='business'),
    path('completed/', views.completed_view, name='completed'),
    path('contact/', views.contact_view, name='contact'),
    path('corporate/', views.corporate_view, name='corporate'),
    path('csr/', views.csr_view, name='csr'),
    path('entreprise/', views.entreprise_view, name='entreprise'),
    path('expressions/', views.expressions_view, name='expressions'),
    path('images/', views.images_view, name='images'),
    path('', views.index_view, name='index'),  # Assuming index.html is the homepage
     path('index', views.index_view, name='index'),
      path('index/', views.index_view, name='index'),
    path('login/', views.login_view, name='login'),
    path('management/', views.management_view, name='management'),
    path('mandate/', views.mandate_view, name='mandate'),
    path('mechanism/', views.mechanism_view, name='mechanism'),
    path('news/', views.news_view, name='news'),
    path('plan/', views.plan_view, name='plan'),
    path('policy/', views.policy_view, name='policy'),
    path('portal/', views.portal_view, name='portal'),
    path('privatisation/', views.privatisation_view, name='privatisation'),
    path('process/', views.process_view, name='process'),
    path('proposal/', views.proposal_view, name='proposal'),
    path('recent/', views.recent_view, name='recent'),
    path('register/', views.register_view, name='register'),
    path('research/', views.research_view, name='research'),
    path('search/', views.search_view, name='search'),
    path('status/', views.status_view, name='status'),
    path('success/', views.success_view, name='success'),
    path('tenders/', views.tenders_view, name='tenders'),
    path('text/', views.text_view, name='text'),
    path('vacancies/', views.vacancies_view, name='vacancies'),
    path('videos/', views.videos_view, name='videos'),
    path('message/',views.message,name='message'),
    path('create_account/',views.create_account,name='create_account'),
    path('auth_login/',views.auth_login,name='auth_login'),
    path('logout',views.logout,name='logout'),
    path('downloads',views.downloads,name='downloads'),
    path('admin-login/', views.redirect_to_admin, name='admin_login'),
]
